
#General settings
[General]
	#Ignore speed boosts for field of view
	#Range: 100 ~ 10000000
	armorStandMaxPower = 1000000

[Modules]

	[Modules."Energy Storage"]

		[Modules."Energy Storage".battery_basic]
			#Range: 0.0 ~ 1.7976931348623157E308
			base_maxEnergy = 1000000.0
			isAllowed = true
			#Range: 0.0 ~ 1.7976931348623157E308
			base_maxTransfer = 1000000.0

		[Modules."Energy Storage".battery_advanced]
			#Range: 0.0 ~ 1.7976931348623157E308
			base_maxEnergy = 5000000.0
			isAllowed = true
			#Range: 0.0 ~ 1.7976931348623157E308
			base_maxTransfer = 5000000.0

		[Modules."Energy Storage".battery_elite]
			#Range: 0.0 ~ 1.7976931348623157E308
			base_maxEnergy = 5.0E7
			isAllowed = true
			#Range: 0.0 ~ 1.7976931348623157E308
			base_maxTransfer = 5.0E7

		[Modules."Energy Storage".battery_ultimate]
			#Range: 0.0 ~ 1.7976931348623157E308
			base_maxEnergy = 1.0E8
			isAllowed = true
			#Range: 0.0 ~ 1.7976931348623157E308
			base_maxTransfer = 1.0E8

